### PR TITLE
PR for Issue_905 -iversonLv- X to close Badges pop up is too far to the right

### PR DESCRIPTION
**Pull request by iversonLv**
PR for issue #905

### CODE REVIEW

**Comment by iversonLv** [comment]
I think I don't need worry about the above "All checks have failed"?

**Comment by talesforce** [comment]
@iversonLv - I am not sure on the Travis part. 

@ajefts - can you confirm that?

**Comment by vikasrohit** [comment]
@iversonLv Please take latest from upstream. It should fix the unit tests.

**Comment by iversonLv** [comment]
I pulled the latest commit and raise PR again, is it fine?

**Comment by iversonLv** [comment]
Seems checked passed now? and the no conflicts..

**Comment by talesforce** [comment]
Yes, thank you @iversonLv !

**Pull request merged**
