### PR TITLE
fixes #912 added predix coder badge

### LINKED ISSUE #912: [$30] - Add Predix badges to profiles

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed #912 added predix coder badge

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@shubhendusaurabh The way the badge is shown in the page is totally fine. I want to ask you to double check the way you scale the badge and compress the entire sprite image. Now the badge looks like it is a bit dirty, and has a darker spot on the blue section in the central part. Can we improve it?

**Comment by shubhendusaurabh** [comment]
@birdofpreyru I first resized the predix badge into 48x48 dimensions. And then added it to the sprite via GIMP. If you have any suggestions, how I can improve it please tell.

**Comment by birdofpreyru** [comment]
@shubhendusaurabh I believe, you'll achieve better result if you use Inkscape. Import the initial `.png` sprite there, and use the `.svg` version of the badge (which is vector image, thus better scalable) to insert into the sprite, then export it all into the new `.png` sprite of the correct size (the same, as now). Or, if you encounter any problems on the way, you also may scale the `.svg` badge to the target size first, using the Inkscape, then export it to `.png`, and then use Gimp to paste it into the sprite.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru I was able to improve it slightly using your first method. Is this ok?
sprite

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Yeap, this looks perfect! Please, push the updated sprite into this branch.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru updated

**Pull request merged**
