### PR TITLE
fixed #675 change max-length to min-length

### LINKED ISSUE #675: $25 - My Challenges--All blue line should be of same size on IE 11
JIRA: https://appirio.atlassian.net/browse/SUP-2699

** Steps to reproduce** 
1. Login as iamtong on IE 11.
2. Open my challenges.
3. Verify the blue line on card.
capture-for-jira-screenshot-20151118-232958-325

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed #675 changed max-length to min-length since difference in heights was because of variable challenge name lengths

### CODE REVIEW

**Comment by nlitwin** [comment]
@vikasrohit I'm not able to reproduce the original problem. Vikas, in the JIRA ticket, did you say that you might have already fixed this in another change ?

**Comment by vikasrohit** [comment]
If you are not able to reproduce the issue, I think it is fixed with the change made for SUP-2412 because we have changed the implementation of rendering the track bar. It is now a simple border of the div in contrast to a div filled with color and placed relatively in its parent div.
The change made for this issue seems to be incorrect to me because the aim behind setting max-height for the hyperlink, containing the challenge name, is to truncate or ellipsis(it is not done yet) the challenge name when it is occupying more than 3 rows.
And the variable blue line, among different cards, is acceptable. Right @vic-appirio ? 

So, in nut shell, I think we don't need any fix for this issue if we are not able to reproduce the original issue in IE. And we should close this PR without merging.

**Comment by shubhendusaurabh** [comment]
If variable blue line is acceptable then we can close this PR

**Comment by huangqun** [comment]
@vikasrohit Could you please confirm if variable blue line is acceptable and whether we should close this one without merging?

**Comment by vikasrohit** [comment]
@huangqun @shubhendusaurabh if the original issue (coloured lines overflowing the headers for single card) mentioned for IE11 is not happening now, it can be closed.

**Pull request closed without merging**
