### PR TITLE
SUP-1005 challenge api refactor

### PR DESCRIPTION
**Pull request by vikasrohit**
@parthshah  @nlitwin @tladendo 

I have two options for creating tc-pager directive, one is to use broadcast-on based event model and another is to watch the scope variables to communicate between controller and directive. I have chosen the later on for now because I found some odds against former one e.g. when we have to handle only one or two scopes, it is better not to pollute the global scope with broadcast events. Please let me know your thoughts.

### CODE REVIEW

**Comment by vikasrohit** [comment]
Merging for now to check if it conflicts with any new development in the dev branch. Please feel free to provide your valuable feedback in case you find any thing out of league.

**Comment by parthshah** [comment]
hi @vikasrohit , 
This is great stuff! I agree, best to use scope variables in this case. I found a couple of oddities when switching b/w active and past filters though.
1. limit  / offset is be carried over when switching b/w active / past filters. This logic breaks for the following eg. User 'albertwang' has 771 past challenges. Let's say I am on page 4. If I switch to Active tab , it attempts to load active challenges with limit / offset values from "past" filter. We should either store limit / offset for each filter or to keep things simpler - reset the values.

I'll review this with Anuj tomorrow as well and provide you some more feedback. Can we rename tc-pager -> tc-pagination? The name is slightly confusing, I though pager was some sort of notification thingy :).
But overall - :+1:

**Comment by vikasrohit** [comment]
Created ticket for the issue [SUP-1346](https://appirio.atlassian.net/browse/SUP-1346) and I would rename the directive too as tc-paginator as per our offline discussion.

**Comment by vikasrohit** [comment]
Btw, it was very nice catch! Thanks :)

**Pull request merged**
