### PR TITLE
fixed #694 added tco16 url

### LINKED ISSUE #694: $25 - Add TCO icon/link to the navigation
JIRA ticket: https://appirio.atlassian.net/browse/SUP-2952

This change must be done on multiple repositories.

Task: 

Add TCO icon under Community, second in the order (behind "Overview"). The icon should link to: http://tco16.topcoder.com/.

The icons should be under ~/topcoder-app/assets/images/nav  
Position: Community, after Overview
Icon: ico-tco16.svg; Title: TCO 2016, URL: http://tco16.topcoder.com/

screen shot 2016-01-26 at 3 34 25 pm

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixed #694 added tco 2016 nav url

### CODE REVIEW

**Comment by parthshah** [comment]
@nlitwin please review and merge today.

**Comment by huangqun** [comment]
@shubhendusaurabh could you resolve the merge conflicts and submit a new PR?

**Comment by nlitwin** [comment]
Sorry about this one. I didn't see the comment to look at this one today. I will do it first thing in the morning, and I can fix the merge conflicts too.

**Comment by vikasrohit** [comment]
@huangqun @shubhendusaurabh  @nlitwin  I am working on resolving the conflicts. I would update once I am done.

**Comment by vikasrohit** [comment]
I have resolved the conflicts, however, I am not able to push changed into the target branch. Its throwing 403 to me.

**Comment by vikasrohit** [comment]
Created new [PR](https://github.com/appirio-tech/topcoder-app/pull/709) with resolved conflicts.

**Comment by vikasrohit** [comment]
@ajefts @fnisen Icon seems to be smaller than what is proposed in original screenshot in the issue #694 . Here is how it is looking after these changes:
screen shot 2016-02-03 at 3 15 05 pm

cc: @shubhendusaurabh @parthshah @nlitwin

**Pull request merged**
