### PR TITLE
fixes #906 infinite scolling for user challenges

### LINKED ISSUE #906: [$60] - Replace "Load More" with infinite scroll
On Challenges/Contests (https://www.topcoder.com/my-challenges/?status=completed), after first "Load More," we should switch to infinite scroll, as we do on Member Search

### PR DESCRIPTION
**Pull request by shubhendusaurabh**
fixes #906 infinite scolling for user challenges

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Hey, I wonder, whether have you managed to locally run the App against the production database, or have you come with other ideas how to test it? It turns out to be a bit trickier, than I expected.

**Comment by shubhendusaurabh** [comment]
@birdofpreyru What I did was to change `API_URL` and `API_URL_V2` to production URLs directly in `appirio-tech-webpack-config` module. So for auth dev API was used and for the profile, production API was used. And for my-challenges, replaced `vm.handle' with my handle.

I also spent more time figuring out how to run the app with production API rather than fixing the issue. :tired_face:

**Comment by birdofpreyru** [comment]
@shubhendusaurabh Hey, sorry for a delay with reviewing your submission.

On the `/my-challenges` route it works just perfect.

On the `/members/HANDLE/details/?track=...` it still shows and demands to click the `LOAD MORE` button the first time you I scroll down the list. After I click it, it works perfect (when I scroll to the new end of the list, no need for clicking anything again). Thus, I just want to ask you a small change: please, remove this `LOAD MORE` button, so that the page `/members/HANDLE/details/?track=...` works the same as the `/my-challenge` one: just an infinite scrolling from the very beginning.

Also, as I see it working fine, let's increase the `CHALLENGES_LOADING_CHUNK` to 36

**Comment by shubhendusaurabh** [comment]
@birdofpreyru updated

**Pull request merged**
