### PR TITLE
Add a Complete appeals button on challenge card

### LINKED ISSUE #958: [$40] - Add a COMPLETE APPEALS button when the appeals phase is open
Currently the **Appeals Phase** takes 24h and in most cases there are only few appeals.
Most members don't know or they just ignore the fact that they can actually click that button in the Online Review to close the Appeals phase sooner. 

I believe we should add a **Notification/link** on the challenge details page when the Appeals phase is open to tell the user that he/she can go and complete the appeals and close the phase sooner.

### PR DESCRIPTION
**Pull request by ThomasKranitsas**
Closes #958 

Demo video: http://take.ms/cShsa

### CODE REVIEW

**Comment by birdofpreyru** [comment]
Wow! The really cool addition to the website? :)
And right in time! I'm having a challenge approaching appeals phase soon, will test it also :)
Does add the buttons to the cards in the list view as well?

**Comment by ThomasKranitsas** [comment]
Yep! Both challenge cards and list view :)
Note that when you deploy locally the links will be like `https://software.topcoder-dev.com/....` so you will get an error but if you remove the -dev from the URL it will show the correct page.

**Comment by ThomasKranitsas** [comment]
When this will be pushed to production this issue with the -dev in the URL will be resolved

**Comment by birdofpreyru** [comment]
Yeap, I got it.

**Pull request merged**
