### PR TITLE
Tco16 nav url conflict fix

### PR DESCRIPTION
**Pull request by vikasrohit**
-- Resolved conflicts for [PR](https://github.com/appirio-tech/topcoder-app/pull/697)

@parthshah @nlitwin @huangqun @shubhendusaurabh fyi

### CODE REVIEW

**Comment by huangqun** [comment]
@vikasrohit in the original PR I can see changes to config.js, but I don't see these in this new PR, don't we need to add TCO16_URL to config.js?

Thanks!

**Comment by vikasrohit** [comment]
Yes, we have moved the constants to another [repo](https://github.com/appirio-tech/webpack-config). I have made changes there.

**Comment by huangqun** [comment]
@vikasrohit should we accept this PR then? I saw you commented in the issue saying the logo looks smaller compared to the others, not sure if that's going to be an issue?

**Comment by vikasrohit** [comment]
@huangqun I think it would be an issue because as per design it should be little larger. @vic-appirio Can you please check image attached [here](https://github.com/appirio-tech/topcoder-app/pull/697) in my last comment and let us know if it is ok to proceed with current implementation?

**Comment by shubhendusaurabh** [comment]
@vikasrohit thanks for fixing the conflicts :+1: 
size issue can easily be fixed by increasing height/width or scale property.
tco16

if this looks good i can submit new PR after this one is merged or rebase on this branch.

**Comment by vic-appirio** [comment]
No problems with the design - the screenshot looks great. I'm a go for merging!

**Comment by vikasrohit** [comment]
Ok @vic-appirio. Just for aggregating all information at same place, here is the final output of current implementation.
screen shot 2016-02-03 at 3 15 05 pm

**Pull request merged**
