### PR TITLE
Misc bug fixes

### PR DESCRIPTION
**Pull request by ThomasKranitsas**
Challenge https://www.topcoder.com/challenge-details/30056070/?type=develop

Fixes:
-[x] Dashboard - Challenge card links do not work
-[x] Fix Responsiveness - Community Overview page
-[x] Replace "Load More" with infinite scroll for Challenges page

### CODE REVIEW

**Comment by ThomasKranitsas** [comment]
I pushed another commit to fix a lint error (`extra-semicolon`)

**Comment by talesforce** [comment]
@ThomasKranitsas - Can you please do a git pull and raise this PR again? The tests seems to be failing right now.

**Comment by tladendo** [comment]
@ThomasKranitsas @talesforce: these commits appear to be breaking the build. Can someone check in on this?

**Comment by ThomasKranitsas** [comment]
@tladendo I can check that, but tomorrow as it's late in my local timezone

**Comment by tladendo** [comment]
@ThomasKranitsas @talesforce: that was my mistake, actually some else's commits broke the build! So these commits are actually fine.

**Pull request merged**
