### PR TITLE
Fix submitted by  shubhendus for skill picker challenge

### PR DESCRIPTION
**Pull request by sushilshinde**
@birdofpreyru please review 

Reference : [IMPROVE CONVERSION ON SKILL PICKER PAGE - PHASE I](https://www.topcoder.com/challenge-details/30059764/?type=develop)

### CODE REVIEW

**Comment by birdofpreyru** [comment]
@sushilshinde I've tried with a fresh user in prod; this seems to work fine, but I have a few doubts:
1. To make the first change you've asked (to make community selection always visible), the author of this fix has removed these two lines:
  ```
  community.display = false
  community.status = true
  ```
  right under this comment in code:
  ```
  // set display false to avoid showing already enabled/registered program
  // we expect display property to be modified after first load  of the page
  ```
  I am not sure what exactly going on there (and had no time to really check the code); but it looks like the initial rendering of community selection was disabled intentionally on some purpose; I wonder is it fine to just enable it the way it is enable now?

2. Are you sure about the new validation logic for Done button? Allowing to press it when at least one compeition track is selected (as before), looks to me a way more logical than the new condition (when at least one community is selected).

**Comment by sushilshinde** [comment]
@birdofpreyru 
#1
Skill picker page will be shown only once in the lifespan of an account unless somebody is going directly via URL. So first time user will never have any data present. These lines only will be executed if the user visits again directly via URL, which will never be the case. So commenting them, will not make any difference.

#2 
This validation logic I discussed with @ajefts . As we want users to select community (Cognitive in this case) without any efforts order to improve conversion/signups. Other options like tracks and skills can be edited from profile page later. For now, our focus is to use this page for default signups.

**Comment by birdofpreyru** [comment]
@sushilshinde what about ppl who just register for the main TC site, I guess they are taken to the same skill picker page? For them it might be confusing that they have to select at least one community, which of them are quite specific.

**Comment by sushilshinde** [comment]
@birdofpreyru will chat on this.

**Pull request merged**
