### PR TITLE
PR for issue_905 -iversonLv- another solution: hide X button and click ..v2

### PR DESCRIPTION
**Pull request by iversonLv**
PR for issue #905 

@birdofpreyru maybe the cache bug, please check again?
Thanks.

### CODE REVIEW

**Comment by birdofpreyru** [comment]
Still does not seem to work on clicks

**Comment by birdofpreyru** [comment]
Probably, the area we think about as about the background, is not technically the background in the current implementation, thus the clicks never reach the directive?

**Comment by iversonLv** [comment]
Don't know why sometimes the app not work (win10). I used .nvmrc node version(5.0) and npm install, it says some optional dependency is not supported and npm start,

In fact I face same problem for another topcoder challenge (topcoder site)

image

**Comment by birdofpreyru** [comment]
@iversonLv I've Googled about this error, and it seems it is a bug in some of dependencies. Have a look if these recipes help:
https://github.com/callemall/material-ui/issues/3200
https://github.com/keystonejs/keystone/issues/3329
Also, probably, updating some of the dependencies to the more recent versions will help (though, probably may break something else).

**Comment by iversonLv** [comment]
thanks for your info will check it out'... seems some other members have similar problems.

**Comment by birdofpreyru** [comment]
Yeap, I've seen the thread you refer to, and also have commented the same there.
Unfortunately, I can't test it right now on Windows myself, and it does not happen on Ubuntu.

**Comment by birdofpreyru** [comment]
@iversonLv I have tried myself to run this App on Windows, and it seems pretty impossible without severely updating all dependencies, which is out of question now. Thus, don't you mind, if I open this issue's ticket for pick-up by anybody else?

**Comment by iversonLv** [comment]
could you please wait for one day today I could get a mac for testing.
Thanks.

**Comment by birdofpreyru** [comment]
Ok. Or maybe just try to co-install Ubuntu on your Windows machine :)

**Comment by iversonLv** [comment]
@birdofpreyru sorry, could not solve the environment problem.....
In fact I try Ubuntu on windows, but I don't know how to fixed wifi problem....

**Comment by birdofpreyru** [comment]
Ok. So, then I'll open it in the Bug Bash, which is coming. Sorry about that :/

**Pull request closed without merging**
