### PR TITLE
PR for issue_905 -iversonLv- another solution: hide X button and click overl…

### PR DESCRIPTION
**Pull request by iversonLv**
…ay to cclose the badge modal dialog

PR for issue #905

### CODE REVIEW

**Comment by ajefts** [comment]
@iversonLv Is this what we should instead of the previous PR?  Or do I need to pull in both for this to work?  Thanks.

**Comment by birdofpreyru** [comment]
@ajefts Wait a sec, I'm writing a response in the original issue

**Comment by birdofpreyru** [comment]
This one seems to not work anyway.

**Comment by birdofpreyru** [comment]
I.e. it closes the modal by pressing Esc on the keyboard, but does not close on mouse clicks outside the content.

**Comment by iversonLv** [comment]
Forgot this one, I merge some herku testing file.

**Pull request closed without merging**
