### PR TITLE
Add optional for now so we can deploy

### PR DESCRIPTION
**Pull request by nlitwin**

### CODE REVIEW

**Comment by vikasrohit** [comment]
@nlitwin do you know why this error appeared? Did we removed tc-btn from appirio-styles? And if we include `@import 'topcoder/tc-buttons';`, we can get rid of this error without making it optional.

**Comment by nlitwin** [comment]
I think the error is that there is no standalone `.tc-btn` class anymore. It was changed awhile ago to be `button.tc-btn`. I think that is the error, but I'm not sure why it's showing up now after all this time.

**Comment by nlitwin** [comment]
I think I fixed the error as well as fix the intro js CSS that has been broken for half a year lol

**Comment by vikasrohit** [comment]
I thought of the same reason, but it is not due the missing standalone class, rather it is due to missing import of tc-buttons.

**Pull request merged**
